### ISSUE TITLE
No constructor found error with IE11 + MX 7.15.1

### ISSUE THREAD

**Issue by YasmijnNL** [mendix/ClipboardTextCopy#3]
The 'no constructor found' error appears in IE 11 when this widget is used in MX 7.15.1. 
In i.e. Google Chrome the error does not occur.

**Comment by bbredewold** [comment]
Seems there is already a Pull request for this... https://github.com/mendix/ClipboardTextCopy/pull/6
Can this be reviewed please?

**Comment by JelteMX** [comment]
Version [1.1.1](https://github.com/mendix/ClipboardTextCopy/releases/tag/v1.1.1) contains the fix, closing issue
